version: "3.9"
services:
  api:
    build: ./api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  web:
    working_dir: /web
    image: node:20-alpine
    command: sh -c "npm i && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./web:/web
    environment:
      - VITE_API_BASE=http://localhost:8000
